name: leigod auto pause action
on:
  push:
  workflow_dispatch:
  schedule:
    # 定时任务，北京时间3点执行任务 19 + 8 = 27 % 24 = 3
    - cron: '0 6 * * *'

jobs:
  pause:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Run npm install
        run: |
          npm install
      - name: Run node index.js
        run: |
          node index.js
        env:
          USERNAME_ARR: ${{ secrets.USERNAME_ARR }}
          PASSWORD_ARR: ${{ secrets.PASSWORD_ARR }}
